### ISSUE TITLE
Support `-c` and `--config` with Config File

### ISSUE THREAD

**Issue by Yousef-Majidi** [omalk98/TILvert#11]
I'd like to contribute to your project by adding support for specifying a `TOML` formatted config file instead of having to pass all of their options as command line arguments. 

For example, consider the following config file, ./config.toml:

```toml
output = "./build"
stylesheet = "https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"
lang = "fr"
```

A user could run the cli by doing either of the following:

```bash
# Option 1: use command line arguments:
til ./site --output ./build --stylesheet https://cdn.jsdelivr.net/npm/water.css@2/out/water.css --lang fr

# Option 2: use a config file
til ./site --config ./config.toml
```
